/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataArrivalReportDAO;
import controller.PaymentResumeReportDAO;
import controller.ProductArrivalReportDAO;
import java.io.File;
import java.sql.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class DateDialog extends javax.swing.JDialog {

    /**
     * Creates new form DateDialog
     */
    int type;

    public DateDialog(java.awt.Frame parent, boolean modal, int type) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        getRootPane().setDefaultButton(acceptButton);
        this.type = type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beginDateChooser = new com.toedter.calendar.JDateChooser();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        beginDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        beginDateChooser.setDate(new java.util.Date());
        beginDateChooser.getDateEditor().setEnabled(false);

        endDateChooser.setDate(new java.util.Date());
        endDateChooser.getDateEditor().setEnabled(false);

        beginDateLabel.setText("Fecha inicio:");

        endDateLabel.setText("Fecha fin:");

        acceptButton.setText("ACEPTAR");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("CANCELAR");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beginDateLabel)
                    .addComponent(endDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beginDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beginDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        Date beginDate = new Date(beginDateChooser.getDate().getTime());
        Date endDate = new Date(endDateChooser.getDate().getTime());
        if (type == 1) {
            try {
                List list = ProductArrivalReportDAO.listOfProductArrivalReports(beginDate, endDate);

                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/productArrivalReport.jasper"));

                JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(list));

                JasperViewer frame = new JasperViewer(jasperPrint, false);

                frame.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(DateDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (type == 0) {
            try {
                List list = PaymentResumeReportDAO.listOfPaymentResumeReports(beginDate, endDate);

                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/paymentResumeReport.jasper"));

                JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(list));

                JasperViewer frame = new JasperViewer(jasperPrint, false);

                frame.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(DateDialog.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (type == 2) {
            try {
                List list = DataArrivalReportDAO.listOfDataArrivalReports(beginDate, endDate);

                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/dataArrivalReport.jasper"));

                JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(list));

                JasperViewer frame = new JasperViewer(jasperPrint, false);

                frame.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(DateDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();

    }//GEN-LAST:event_acceptButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private com.toedter.calendar.JDateChooser beginDateChooser;
    private javax.swing.JLabel beginDateLabel;
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JLabel endDateLabel;
    // End of variables declaration//GEN-END:variables
}
