/*
 * Copyright (c) 2015 Pastor Tantalean.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Pastor Tantalean - initial API and implementation and/or initial documentation
 */
package view;

import controller.BalanceReportDAO;
import controller.SaleDAO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.Permission;
import model.Sale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Pastor Tantalean
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     *
     * @param list
     */
    public MainFrame(List<Permission> list) {
        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        init();

        for (Permission p : list) {
            switch (p.getPermissionID()) {
                case 1:
                    warehouseMenu.setVisible(true);
                    break;
                case 2:
                    reportsMenu.setVisible(true);
                    break;
                case 3:
                    saleMenu.setVisible(true);
                    break;
                case 4:
                    usersMenu.setVisible(true);
                    break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        warehouseMenu = new javax.swing.JMenu();
        warehouseMaintenanceMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        balanceMenuItem = new javax.swing.JMenuItem();
        dataArrivalMenuItem = new javax.swing.JMenuItem();
        saleMenu = new javax.swing.JMenu();
        newSaleMenuItem = new javax.swing.JMenuItem();
        cancelSaleMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        productArrivalMenuItem = new javax.swing.JMenuItem();
        paymentResumeMenuItem = new javax.swing.JMenuItem();
        reportsSeparator = new javax.swing.JPopupMenu.Separator();
        kardexMenuItem = new javax.swing.JMenuItem();
        usersMenu = new javax.swing.JMenu();
        newUserMenuItem = new javax.swing.JMenuItem();
        updateUserMenuItem = new javax.swing.JMenuItem();
        deleteUserMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        desktopPane.setBackground(new java.awt.Color(29, 29, 29));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");
        fileMenu.setToolTipText("");

        logoutMenuItem.setMnemonic('a');
        logoutMenuItem.setText("Cerrar Sesión");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        warehouseMenu.setMnemonic('e');
        warehouseMenu.setText("Almacén");

        warehouseMaintenanceMenuItem.setMnemonic('t');
        warehouseMaintenanceMenuItem.setText("Mantenimiento Almacén");
        warehouseMaintenanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseMaintenanceMenuItemActionPerformed(evt);
            }
        });
        warehouseMenu.add(warehouseMaintenanceMenuItem);
        warehouseMenu.add(jSeparator2);

        balanceMenuItem.setText("Saldos Totalizados/Inventario");
        balanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceMenuItemActionPerformed(evt);
            }
        });
        warehouseMenu.add(balanceMenuItem);

        dataArrivalMenuItem.setText("Datos de Ingresos de Medicamentos");
        dataArrivalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataArrivalMenuItemActionPerformed(evt);
            }
        });
        warehouseMenu.add(dataArrivalMenuItem);

        menuBar.add(warehouseMenu);

        saleMenu.setMnemonic('h');
        saleMenu.setText("Venta");

        newSaleMenuItem.setMnemonic('c');
        newSaleMenuItem.setText("Nueva Venta");
        newSaleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSaleMenuItemActionPerformed(evt);
            }
        });
        saleMenu.add(newSaleMenuItem);

        cancelSaleMenuItem.setText("Anular Venta");
        cancelSaleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSaleMenuItemActionPerformed(evt);
            }
        });
        saleMenu.add(cancelSaleMenuItem);

        menuBar.add(saleMenu);

        reportsMenu.setText("Reportes");

        productArrivalMenuItem.setText("Ingresos de Medicamentos");
        productArrivalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productArrivalMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(productArrivalMenuItem);

        paymentResumeMenuItem.setText("Resumen de Pagos");
        paymentResumeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentResumeMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(paymentResumeMenuItem);
        reportsMenu.add(reportsSeparator);

        kardexMenuItem.setText("Kárdex");
        kardexMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kardexMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(kardexMenuItem);

        menuBar.add(reportsMenu);

        usersMenu.setText("Usuarios");

        newUserMenuItem.setText("Nuevo Usuario");
        newUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserMenuItemActionPerformed(evt);
            }
        });
        usersMenu.add(newUserMenuItem);

        updateUserMenuItem.setText("Actualizar Usuario");
        updateUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserMenuItemActionPerformed(evt);
            }
        });
        usersMenu.add(updateUserMenuItem);

        deleteUserMenuItem.setText("Eliminar Usuario");
        deleteUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserMenuItemActionPerformed(evt);
            }
        });
        usersMenu.add(deleteUserMenuItem);

        menuBar.add(usersMenu);

        helpMenu.setText("Ayuda");

        contentsMenuItem.setText("Contenidos");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void warehouseMaintenanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseMaintenanceMenuItemActionPerformed
        JInternalFrame frame = new JInternalFrame("Mantenimiento Almacén", true, true, true, true);
        //frame.setLocation((int) getAlignmentX(), (int) getAlignmentY());
        WarehouseMaintenancePanel panel = new WarehouseMaintenancePanel();
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        desktopPane.add(frame);
        //frame.setResizable(false);
        frame.setMaximizable(false);

        Dimension dpSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();

        frame.setLocation((dpSize.width - frameSize.width) / 2, (dpSize.height - frameSize.height) / 2);

        frame.setVisible(true);
    }//GEN-LAST:event_warehouseMaintenanceMenuItemActionPerformed

    private void newSaleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSaleMenuItemActionPerformed
        JInternalFrame frame = new JInternalFrame("Nueva Venta", true, true, true, true);
        //frame.setLocation((int) getAlignmentX(), (int) getAlignmentY());
        NewSalePanel panel = new NewSalePanel(frame);
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        desktopPane.add(frame);
        frame.setResizable(false);
        frame.setMaximizable(false);

        Dimension dpSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();

        frame.setLocation((dpSize.width - frameSize.width) / 2, (dpSize.height - frameSize.height) / 2);

        frame.setVisible(true);
    }//GEN-LAST:event_newSaleMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        dispose();
        LoginFrame frame = new LoginFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void newUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserMenuItemActionPerformed
        JInternalFrame frame = new JInternalFrame("Agregar Usuario", true, true, true, true);
        //frame.setLocation((int) getAlignmentX(), (int) getAlignmentY());
        NewUserPanel panel = new NewUserPanel();
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        desktopPane.add(frame);
        frame.setResizable(false);
        frame.setMaximizable(false);

        Dimension dpSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();

        frame.setLocation((dpSize.width - frameSize.width) / 2, (dpSize.height - frameSize.height) / 2);

        frame.setVisible(true);
    }//GEN-LAST:event_newUserMenuItemActionPerformed

    private void updateUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserMenuItemActionPerformed
        JInternalFrame frame = new JInternalFrame("Actualizar Usuario", true, true, true, true);
        //frame.setLocation((int) getAlignmentX(), (int) getAlignmentY());
        UpdateUserPanel panel = new UpdateUserPanel();
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        desktopPane.add(frame);
        frame.setResizable(false);
        frame.setMaximizable(false);

        Dimension dpSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();

        frame.setLocation((dpSize.width - frameSize.width) / 2, (dpSize.height - frameSize.height) / 2);

        frame.setVisible(true);
    }//GEN-LAST:event_updateUserMenuItemActionPerformed

    private void deleteUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserMenuItemActionPerformed
        JInternalFrame frame = new JInternalFrame("Eliminar Usuario", true, true, true, true);
        //frame.setLocation((int) getAlignmentX(), (int) getAlignmentY());
        DeleteUserPanel panel = new DeleteUserPanel();
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        desktopPane.add(frame);
        //System.err.println(getLocation().getX() + " - " + getLocation().getY());
        frame.setLocation(250, 190);
        frame.setResizable(false);
        frame.setMaximizable(false);

        Dimension dpSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();

        frame.setLocation((dpSize.width - frameSize.width) / 2, (dpSize.height - frameSize.height) / 2);

        frame.setVisible(true);
    }//GEN-LAST:event_deleteUserMenuItemActionPerformed

    private void cancelSaleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSaleMenuItemActionPerformed
        String search = JOptionPane.showInternalInputDialog(cancelSaleMenuItem, "Ingrese el número de comprobante");
        Sale s = SaleDAO.existSale(search);
        if (s == null) {
            JOptionPane.showInternalMessageDialog(cancelSaleMenuItem, "No existe la venta realizada con comprobante: " + search + ".");
        } else {
            SaleListDialog frame = new SaleListDialog(this, rootPaneCheckingEnabled, search, s);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_cancelSaleMenuItemActionPerformed

    private void productArrivalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productArrivalMenuItemActionPerformed
        DateDialog frame = new DateDialog(this, rootPaneCheckingEnabled, 1);
        frame.setVisible(true);
    }//GEN-LAST:event_productArrivalMenuItemActionPerformed

    private void paymentResumeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentResumeMenuItemActionPerformed
        DateDialog frame = new DateDialog(this, rootPaneCheckingEnabled, 0);
        frame.setVisible(true);
    }//GEN-LAST:event_paymentResumeMenuItemActionPerformed

    private void balanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceMenuItemActionPerformed
       try {
            List list = BalanceReportDAO.listOfBalanceReports();

            JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/balanceReport.jasper"));

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(list));

            JasperViewer frame = new JasperViewer(jasperPrint, false);

            frame.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(DateDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_balanceMenuItemActionPerformed

    private void kardexMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kardexMenuItemActionPerformed
        ConsultDialog frame = new ConsultDialog(this, rootPaneCheckingEnabled);
        frame.setVisible(true);
    }//GEN-LAST:event_kardexMenuItemActionPerformed

    private void dataArrivalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataArrivalMenuItemActionPerformed
        DateDialog frame = new DateDialog(this, rootPaneCheckingEnabled, 2);
        frame.setVisible(true);
    }//GEN-LAST:event_dataArrivalMenuItemActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem balanceMenuItem;
    private javax.swing.JMenuItem cancelSaleMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem dataArrivalMenuItem;
    private javax.swing.JMenuItem deleteUserMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem kardexMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newSaleMenuItem;
    private javax.swing.JMenuItem newUserMenuItem;
    private javax.swing.JMenuItem paymentResumeMenuItem;
    private javax.swing.JMenuItem productArrivalMenuItem;
    private javax.swing.JMenu reportsMenu;
    private javax.swing.JPopupMenu.Separator reportsSeparator;
    private javax.swing.JMenu saleMenu;
    private javax.swing.JMenuItem updateUserMenuItem;
    private javax.swing.JMenu usersMenu;
    private javax.swing.JMenuItem warehouseMaintenanceMenuItem;
    private javax.swing.JMenu warehouseMenu;
    // End of variables declaration//GEN-END:variables

    private void init() {
        warehouseMenu.setVisible(false);
        reportsMenu.setVisible(false);
        saleMenu.setVisible(false);
        usersMenu.setVisible(false);
    }

}
