/*
 * Copyright (c) 2015 Pastor Tantalean.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Pastor Tantalean - initial API and implementation and/or initial documentation
 */
package view;

import controller.ProductDAO;
import controller.ProofOfPaymentDAO;
import controller.SaleDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sale;
import model.SaleProductDetail;
import util.Constants;

/**
 *
 * @author Pastor Tantalean
 */
public class SaleListDialog extends java.awt.Dialog {

    /**
     * Creates new form SaleListDialog
     */
    DefaultTableModel dtm;
    String search;
    Sale sale;
    List<SaleProductDetail> list;

    public SaleListDialog(java.awt.Frame parent, boolean modal, String search, Sale sale) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.search = search;
        this.sale = sale;
        
        list = SaleDAO.listDetailOfSale(search);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saleTableScrollPane = new javax.swing.JScrollPane();
        saleTable = new javax.swing.JTable();
        proofOfPaymentTextField = new javax.swing.JTextField();
        subtotalTextField = new javax.swing.JTextField();
        igvTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        igvLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        deleteSaleButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        saleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIPCIÓN", "FORMA", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dtm = (DefaultTableModel) saleTable.getModel();
        saleTableScrollPane.setViewportView(saleTable);

        proofOfPaymentTextField.setEditable(false);
        proofOfPaymentTextField.setEnabled(false);

        subtotalTextField.setEditable(false);
        subtotalTextField.setEnabled(false);

        igvTextField.setEditable(false);
        igvTextField.setEnabled(false);

        totalTextField.setEditable(false);
        totalTextField.setEnabled(false);

        subtotalLabel.setText("Subtotal:");

        igvLabel.setText("IGV:");

        totalLabel.setText("Total:");

        dateChooser.setEnabled(false);

        deleteSaleButton.setText("Cancelar Venta");
        deleteSaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSaleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saleTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(proofOfPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(deleteSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(igvTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(subtotalLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(igvLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalLabel)
                                        .addGap(37, 37, 37)
                                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proofOfPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saleTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igvLabel)
                    .addComponent(deleteSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void deleteSaleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSaleButtonMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la venta con comprobante " + proofOfPaymentTextField.getText() + "?");
        if (option == JOptionPane.OK_OPTION) {
            boolean check = ProofOfPaymentDAO.deleteProofOfPayment(sale.getProofOfPayment(), Constants.getUserLoged());
            if (check) {
                for (SaleProductDetail spd : list) {
                    spd.getProduct().setStock(spd.getQuantity());
                    check &= ProductDAO.getProduct(spd.getProduct());
                }
                JOptionPane.showMessageDialog(this, "La venta fue cancelada exitosamente.");
                
            }
        }
    }//GEN-LAST:event_deleteSaleButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton deleteSaleButton;
    private javax.swing.JLabel igvLabel;
    private javax.swing.JTextField igvTextField;
    private javax.swing.JTextField proofOfPaymentTextField;
    private javax.swing.JTable saleTable;
    private javax.swing.JScrollPane saleTableScrollPane;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField subtotalTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        proofOfPaymentTextField.setText(search);
        if (list != null) {
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            for (SaleProductDetail spd : list) {
                double total = spd.getSalePrice() * spd.getQuantity();
                dtm.addRow(new Object[]{spd.getProduct().getDescription(), spd.getProduct().getForm(), spd.getQuantity(), spd.getSalePrice(), total});
            }
            subtotalTextField.setText(sale.getSubtotal() + "");
            igvTextField.setText(sale.getIgv() + "");
            totalTextField.setText(sale.getTotal() + "");
            dateChooser.setDate(sale.getSaleDate());
        }

    }
}
